-- Script SQL para crear 4 iniciativas de prueba en estado Backlog
-- con parámetros aleatorios para testing del sistema de scoring

-- Iniciativa 1: Mandates/Regulatorio con Processing
INSERT INTO initiatives (
    title,
    summary,
    description,
    status,
    category,
    vertical,
    client_type,
    country,
    systemic_risk,
    economic_impact_type,
    innovation_level,
    confidence_level,
    effort_weeks,
    created_by,
    -- Campos nuevos del Kanban
    category_new,
    vertical_new,
    client_type_new,
    country_new,
    systemic_risk_new,
    economic_impact_new,
    economic_impact_description,
    experience_impact_new,
    competitive_approach,
    executive_summary,
    roi
) VALUES (
    'Implementación de Nuevas Regulaciones Fintech',
    'Cumplimiento de nuevas regulaciones del Banco Central para servicios fintech',
    'Esta iniciativa busca implementar todas las nuevas regulaciones emitidas por el Banco Central para servicios fintech, incluyendo KYC mejorado, reportes automáticos y compliance en tiempo real.',
    'Backlog',
    'regulatory',
    'banking',
    'top_issuer',
    'Brazil',
    'high',
    'significant',
    'disruptive',
    8,
    12,
    'test_user_1',
    -- Campos nuevos
    'Mandates / Regulatorio / Riesgo',
    'Processing',
    'Top Issuer',
    'Brasil',
    'Alto',
    'Aumento significativo en revenue o nueva linea revenue',
    'Cumplimiento regulatorio que permitirá expandir servicios a nuevos mercados',
    ARRAY['Contact Rate', 'Aprobación', 'SLA de incidencias'],
    'Disrrustivo / Innovador',
    'Iniciativa crítica para el cumplimiento regulatorio y expansión de mercado en Brasil',
    250
);

-- Iniciativa 2: Mejora de Performance con Core
INSERT INTO initiatives (
    title,
    summary,
    description,
    status,
    category,
    vertical,
    client_type,
    country,
    systemic_risk,
    economic_impact_type,
    innovation_level,
    confidence_level,
    effort_weeks,
    created_by,
    -- Campos nuevos del Kanban
    category_new,
    vertical_new,
    client_type_new,
    country_new,
    systemic_risk_new,
    economic_impact_new,
    economic_impact_description,
    experience_impact_new,
    competitive_approach,
    executive_summary,
    roi
) VALUES (
    'Optimización del Core Banking System',
    'Mejora significativa en la performance del sistema core para reducir latencia',
    'Optimización del sistema core para reducir la latencia de transacciones en un 40%, mejorar la disponibilidad del sistema y reducir costos operativos.',
    'Backlog',
    'performance',
    'banking',
    'major',
    'Mexico',
    'medium',
    'moderate',
    'incremental',
    7,
    8,
    'test_user_2',
    -- Campos nuevos
    'Mejora de performance',
    'Core',
    'Tier 1',
    'Mexico',
    'Medio',
    'Aumento moderado en revenue existente',
    'Mejoras en performance que incrementarán la satisfacción del cliente y reducirán costos',
    ARRAY['SLA de incidencias', 'Aceptación', 'Provisioning Rate'],
    'Mejora incremental',
    'Optimización crítica del sistema core para mejorar performance y reducir costos operativos',
    180
);

-- Iniciativa 3: Value Prop con BIN Sponsor
INSERT INTO initiatives (
    title,
    summary,
    description,
    status,
    category,
    vertical,
    client_type,
    country,
    systemic_risk,
    economic_impact_type,
    innovation_level,
    confidence_level,
    effort_weeks,
    created_by,
    -- Campos nuevos del Kanban
    category_new,
    vertical_new,
    client_type_new,
    country_new,
    systemic_risk_new,
    economic_impact_new,
    economic_impact_description,
    experience_impact_new,
    competitive_approach,
    executive_summary,
    roi
) VALUES (
    'Nueva Plataforma de BIN Sponsorship',
    'Desarrollo de plataforma integral para BIN sponsorship con analytics avanzados',
    'Creación de una plataforma completa para BIN sponsorship que incluya analytics en tiempo real, gestión de riesgo automatizada y onboarding digital.',
    'Backlog',
    'value_prop',
    'banking',
    'medium',
    'Argentina',
    'low',
    'significant',
    'disruptive',
    9,
    16,
    'test_user_3',
    -- Campos nuevos
    'Value Prop',
    'BIN Sponsor',
    'Tier 2',
    'Argentina',
    'Bajo',
    'Aumento significativo en revenue o nueva linea revenue',
    'Nueva línea de negocio que generará revenue significativo a través de BIN sponsorship',
    ARRAY['Contact Rate', 'Aprobación', 'BPS (Chargebacks)'],
    'Disrrustivo / Innovador',
    'Plataforma innovadora de BIN sponsorship que creará nueva línea de revenue',
    320
);

-- Iniciativa 4: Lanzamiento de Nuevo Producto con Tokenización
INSERT INTO initiatives (
    title,
    summary,
    description,
    status,
    category,
    vertical,
    client_type,
    country,
    systemic_risk,
    economic_impact_type,
    innovation_level,
    confidence_level,
    effort_weeks,
    created_by,
    -- Campos nuevos del Kanban
    category_new,
    vertical_new,
    client_type_new,
    country_new,
    systemic_risk_new,
    economic_impact_new,
    economic_impact_description,
    experience_impact_new,
    competitive_approach,
    executive_summary,
    roi
) VALUES (
    'Plataforma de Tokenización de Activos Digitales',
    'Desarrollo de plataforma completa para tokenización de activos digitales',
    'Creación de una plataforma integral para la tokenización de activos digitales, incluyendo smart contracts, marketplace y herramientas de compliance.',
    'Backlog',
    'new_product',
    'banking',
    'startup',
    'Colombia',
    'high',
    'significant',
    'disruptive',
    6,
    20,
    'test_user_4',
    -- Campos nuevos
    'Lanzamiento nuevo producto',
    'Tokenización',
    'Tier 3',
    'Colombia',
    'Alto',
    'Aumento significativo en revenue o nueva linea revenue',
    'Nuevo producto disruptivo que abrirá mercados completamente nuevos',
    ARRAY['Contact Rate', 'Aprobación', 'SLA de envíos', 'Revisión Manual KYC'],
    'Disrrustivo / Innovador',
    'Producto disruptivo de tokenización que posicionará a la empresa como líder en activos digitales',
    450
);

-- Verificar que las iniciativas se crearon correctamente
SELECT 
    id,
    title,
    status,
    category_new,
    vertical_new,
    client_type_new,
    country_new,
    systemic_risk_new,
    economic_impact_new,
    competitive_approach,
    roi
FROM initiatives 
WHERE created_by LIKE 'test_user_%'
ORDER BY created_at DESC;
