version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - wishlist-network

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
      - PORT=8080
      - DATABASE_URL=postgres://wishlist:wishlist@db:5432/wishlist?sslmode=disable
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - wishlist-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=wishlist
      - POSTGRES_USER=wishlist
      - POSTGRES_PASSWORD=wishlist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d/
    networks:
      - wishlist-network

volumes:
  postgres_data:

networks:
  wishlist-network:
    driver: bridge